let map=new Map([[['name'],'sai'],['place','hyderabad'],[26,25]])
console.log('it holdes key value pairs where keys can be any data type',map.set('name','saikiran'))
map.set('apple','red')
// const obj={cource:'java'}
// map.set(obj,'technology')
console.log('it reparsents size of thr map',map)
map.forEach((v,k)=>console.log(k,":",v))
console.log(map.get('name'))
console.log(map.values())
console.log('Map remembers original insertion order of the keys:',map.keys())
console.log(map.entries())
console.log(map.has('age'))
console.log(map.has('place'))
console.log('size of an map is:',map.size)
console.log(map.clear())
console.log('After clear() method it shows undefined',map)